/**
 * Connect DM Helper — single entry point for sending a direct message
 * via shizuha-connect's `/api/messaging/dm/` endpoint.
 *
 * Used by:
 *   - The `message_user` builtin tool (gateway process)
 *   - The daemon `/v1/agents/:id/message` endpoint, when platform is linked
 *
 * Authentication: callers may pass an explicit JWT in `opts.token`. When
 * omitted we obtain the agent's JWT from shizuha-id via `AgentTokenManager`
 * (using AGENT_USERNAME + AGENT_PASSWORD). No local minting — shizuha-id is
 * the only signer.
 */

import * as crypto from 'node:crypto';
import { AgentTokenManager } from '../auth/agent-token-manager.js';

export interface SendConnectDmResult {
  ok: boolean;
  conversationId?: string;
  messageId?: string;
  createdNew?: boolean;
  idempotentReplay?: boolean;
  recipient?: { userId: number; email: string; name: string };
  error?: string;
  status?: number;
}

export interface SendConnectDmOptions {
  /** Recipient email (e.g., "kai@agents.shizuha.io") */
  recipientEmail?: string;
  /** Recipient username — preferred ergonomic form (e.g. "hritik", "kai"). */
  recipientUsername?: string;
  /** Message body (plain text) */
  content: string;
  /** Idempotency key — generated by caller if omitted */
  clientMessageId?: string;
  /** Reply to a specific message (optional) */
  replyToMessageId?: string;
  /** Explicit sender overrides (otherwise read from env vars) */
  sender?: {
    username?: string;
    email?: string;
    userId?: number;
    agentId?: string;
    isAgent?: boolean;
  };
  /** Platform base URL (defaults to SHIZUHA_PLATFORM_URL env) */
  platformUrl?: string;
  /** Explicit JWT (if caller already has one — otherwise self-mint) */
  token?: string;
  /** Optional daemon-side password override when sending as a supervised agent. */
  senderPassword?: string;
  /** Request timeout (ms) */
  timeoutMs?: number;
}

function resolvePlatformBase(override?: string): string {
  // Explicit override wins — callers that pass a URL know their context
  // (e.g., the daemon legitimately runs on the host and can use loopback).
  if (override) return override.replace(/\/+$/, '');

  // Prefer the unified BACKEND_URL — it's the single setting that points at
  // either the real platform (linked) or the daemon's mini-Connect (local).
  // Fall back to legacy SHIZUHA_PLATFORM_URL for backwards compat.
  let base = (process.env['BACKEND_URL'] || process.env['SHIZUHA_PLATFORM_URL'] || '').trim();
  // Reject loopback from env — unusable from inside containers.
  if (!base || base === 'http://localhost' || base.includes('127.0.0.1')) {
    const daemonHost = process.env['DAEMON_HOST'] || 'host.docker.internal';
    const port = process.env['DAEMON_PORT'] || '8016';
    base = `http://${daemonHost}:${port}`;
  }
  return base.replace(/\/+$/, '');
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/**
 * Connect persists client_message_id in a UUIDField. Preserve valid caller
 * UUIDs, generate a fresh UUID when omitted, and deterministically map legacy
 * human-readable idempotency keys to UUIDv5-shaped values. This keeps retries
 * idempotent without sending values that Connect must reject.
 */
export function normalizeConnectClientMessageId(value?: string): string {
  const candidate = (value || '').trim();
  if (!candidate) return crypto.randomUUID();
  if (UUID_RE.test(candidate)) return candidate;

  const bytes = crypto.createHash('sha256').update(candidate, 'utf8').digest().subarray(0, 16);
  bytes[6] = ((bytes[6] ?? 0) & 0x0f) | 0x50;
  bytes[8] = ((bytes[8] ?? 0) & 0x3f) | 0x80;
  const hex = bytes.toString('hex');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20, 32)}`;
}

/**
 * Send a direct message through shizuha-connect.
 *
 * Fire-and-forget semantics: returns as soon as Connect persists + broadcasts.
 * Does NOT wait for the recipient to process the message — that's async and
 * handled by the recipient's own agent loop (if they're an agent) or by their
 * client UI (if they're a human).
 */
export async function sendConnectDm(opts: SendConnectDmOptions): Promise<SendConnectDmResult> {
  const recipientEmail = (opts.recipientEmail || '').trim();
  const recipientUsername = (opts.recipientUsername || '').trim();
  const content = (opts.content || '').trim();
  if (!recipientEmail && !recipientUsername) {
    return { ok: false, error: 'recipient_username or recipient_email required' };
  }
  if (!content) return { ok: false, error: 'content required' };

  const platformBase = resolvePlatformBase(opts.platformUrl);
  if (!platformBase) return { ok: false, error: 'platform URL unresolved' };

  // Either use caller-provided token, or fetch the agent's real shizuha-id
  // JWT (cached + auto-refreshed by AgentTokenManager). No local minting.
  let token = opts.token || '';
  if (!token) {
    const sender = opts.sender || {};
    const username = sender.username || process.env['AGENT_USERNAME'] || '';
    if (!username) {
      return { ok: false, error: 'AGENT_USERNAME not set — cannot authenticate to send DM' };
    }
    try {
      const tm = new AgentTokenManager({
        agentUsername: username,
        agentEmail: sender.email || process.env['AGENT_EMAIL'] || undefined,
        platformUrl: platformBase,
        agentPassword: opts.senderPassword,
      });
      token = (await tm.getToken()) ?? '';
    } catch (err) {
      return { ok: false, error: `shizuha-id login failed: ${(err as Error).message}` };
    }
    if (!token) {
      return { ok: false, error: 'shizuha-id login returned no token (check AGENT_PASSWORD)' };
    }
  }

  const body: Record<string, unknown> = {
    content,
    client_message_id: normalizeConnectClientMessageId(opts.clientMessageId),
  };
  // Username preferred — works against both real Connect and mini-Connect.
  if (recipientUsername) body['recipient_username'] = recipientUsername;
  if (recipientEmail) body['recipient_email'] = recipientEmail;
  if (opts.replyToMessageId) body['reply_to_message_id'] = opts.replyToMessageId;

  const url = `${platformBase}/connect/api/messaging/dm/`;
  const timeoutMs = opts.timeoutMs ?? 10_000;
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const resp = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`,
      },
      body: JSON.stringify(body),
      signal: controller.signal,
    });
    const text = await resp.text();
    let parsed: Record<string, unknown> = {};
    try { parsed = JSON.parse(text); } catch { /* non-JSON error body */ }

    if (!resp.ok) {
      return {
        ok: false,
        status: resp.status,
        error: (parsed['error'] as string) || (parsed['detail'] as string) || text.slice(0, 200),
      };
    }

    const rec = (parsed['recipient'] || {}) as Record<string, unknown>;
    return {
      ok: true,
      status: resp.status,
      conversationId: parsed['conversation_id'] as string,
      messageId: parsed['message_id'] as string,
      createdNew: !!parsed['created_new_conversation'],
      idempotentReplay: !!parsed['idempotent_replay'],
      recipient: {
        userId: Number(rec['user_id'] || 0),
        email: String(rec['email'] || recipientEmail || recipientUsername),
        name: String(rec['name'] || ''),
      },
    };
  } catch (err) {
    return { ok: false, error: (err as Error).message };
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Convenience: resolve a target agent username to the canonical
 * `@agents.shizuha.io` email when callers pass an agent username.
 */
export function agentUsernameToEmail(target: string): string {
  const t = (target || '').trim();
  if (!t) return '';
  if (t.includes('@')) return t;
  return `${t}@agents.shizuha.io`;
}
